name: Publish
on:
    push:
        branches:
            - production

jobs:
    publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - name: Publish package
              run: pnpm dlx jsr publish
